spring.application.name=ucsal-aspmanager-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5000}/${DB_NAME:aspmanager}?sslmode=disable
spring.datasource.username=${DB_USER:aspmanager_user}
spring.datasource.password=${DB_PASSWORD:aspmanager_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false